### ISSUE TITLE
How can I change it to support DiGraph

### ISSUE THREAD

**Issue by ciaojo** [jsexauer/networkx_viewer#5]
Hi, thank you for this interesting Library and great project.
I want to change it to support direct graph?? where is the main draw that draw the graph in the canvas, is it in the graph_canvas file? I want to do sm like this???
![figure_1](https://cloud.githubusercontent.com/assets/4031156/7445828/2bec3936-f1c3-11e4-8e2b-f176e155c141.png)

thank you in advance

**Comment by ciaojo** [comment]
mayby I can use convert_to_directed(MultiGraph) to convert it, but I can't understand where is the main draw function that draw the G in canvas?? thank you

**Comment by ciaojo** [comment]
I saw that you create nodes and lines to draw the graph. I have tried to use arrow but its not working, my code:
    G = nx.MultiGraph()
    G.add_edge('Arg2','Arg1')
    G.add_edge('Arg3','Arg1',0,{'fill':'green', 'arrow':'last'})
    G.add_edge('Arg4','Arg2')
    G.add_edge('Arg5','Arg2')
    G.add_edge('Arg6','Arg3')
    G.node['Arg2']['outline'] = 'blue'
    G.node['Arg1']['label_fill'] = 'red'
 
    app = Viewer(G)
    app.mainloop()

the result graph is the same (with or without 'arrow'), I dont know where is the problem. i want to have an graph to represent nodes with arrows to show which node attack others.

can you help me???
thank you and sorry for all these questions.

**Comment by jsexauer** [comment]
You're on the right track.  The issue is that the node is a canvas widget, which is drawn over the ends of the lines.  The arrow by default is so small that it is hidden by the node.

I've modified the code to support directed graphs, but it's not super pretty.  A better way would be to use a bounding box for the nodes and attach the edges to the ends of the bounding box.  But that's pretty hard.

Here is what my rudimentary support will give you:
```python
### Example 3 ###
G = nx.MultiDiGraph()
G.add_edge('Arg2','Arg1')
G.add_edge('Arg3','Arg1',0)
G.add_edge('Arg3','Arg1',1)
G.add_edge('Arg4','Arg2')
G.add_edge('Arg5','Arg2')
G.add_edge('Arg6','Arg3')
G.node['Arg2']['outline'] = 'blue'
G.node['Arg1']['label_fill'] = 'red'
app = Viewer(G)
app.mainloop()
```

![image](https://cloud.githubusercontent.com/assets/1630128/7447431/c0b56c08-f1c9-11e4-977a-e5904da4ff2d.png)

**Comment by ciaojo** [comment]
thanks a lot for you help ;) . Now i'm trying to modify it to support add nodes and edges. its pretty hard

**Comment by jsexauer** [comment]
If you end up writting something to add nodes, feel free to make a PR.
